<a href="https://colab.research.google.com/github/luispabloaiello-da/git-practice/blob/master/Shark_Mini_Project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#website with the excel file: https://www.sharkattackfile.net/incidentlog.htm

You will initially examine the Shark Attack dataset, understanding its structure and formulating a hypothesis or several hypotheses about the data. For example, you might hypothesize that shark attacks are more common in certain geographical locations, or among individuals engaging in particular activities.

If you want to go further, you could even define a Business Case, such as “As a company that sells diving trips, I want to suggest destination for shark spotting”, or “ As a company that sells surf experiences or surf boards, I want to know where to set up a new shop and avoid shark attacks”.

Throughout the project, you'll utilize Python programming and the pandas library to implement at least five data cleaning techniques to handle issues such as missing values, duplicates, and formatting inconsistencies. Once the dataset is cleaned, you'll use basic exploratory data analysis to validate your initial hypotheses and extract meaningful insights.

**Day 1**

**Dev Team Key Tasks & Topics:**

1. Download the dataset and import it into Python.

2. Examine the data and try to understand what the fields mean before proceeding with data cleaning and manipulation.

3. Analyze the structure and quality of a dataset, identify potential issues or problems, and develop a plan for cleaning and transforming the data.

**Research Team Key Tasks & Topics:**

1. Read self-guided material on business problems, opportunities, problem statements & hypotheses. Also read the self-guided lesson on the MVP (minimum viable product) mindset, scoping and roadmap creation.

2. Share your findings with the Dev Team and decide on a hypothesis (or hypotheses) to guide your data cleaning efforts.
Think about how to present the analysis clearly and coherently to support the findings.

For example: "Sharks attack more younger people than older," "The easiest way to get attacked by a shark is by surfing," "Sharks attack more people in the USA than in Iceland," etc.
Define a roadmap for the quest. The deadline for the quest is on Friday, so it is recommended to divide your cleaning efforts by day. Don’t forget to leave enough time to do basic EDA, clean your code and prepare a presentation. Reviewing the topics by day might help you define the roadmap.

In [ ]:
import pandas as pd

In [ ]:
url = "https://www.sharkattackfile.net/spreadsheets/GSAF5.xls"

In [ ]:
pd.read_excel(url)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,16th August 2025,2025.0,Provoked,USA,Florida,Cayo Costa Boca Grande,Fishing,Shawn Meuse,M,?,...,Lemon shark 1.8 m (6ft),Johannes Marchand: Kevin McMurray Trackingshar...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18th August,2025.0,Unprovoked,Australia,NSW,Cabarita Beach,Surfing,Brad Ross,M,?,...,5m (16.5ft) Great White,Bob Myatt GSAF The Guardian: 9 News: ABS News:...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17th August,2025.0,Unprovoked,Bahamas,Atlantic Ocean near Big Grand Cay,North of Grand Bahama near Freeport,Spearfishing,Not stated,M,63,...,Undetermined,Ralph Collier GSAF and Kevin MCMurray Tracking...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7th August,2025.0,Unprovoked,Australia,NSW,Tathra Beach,Surfing,Bowie Daley,M,9,...,Suspected Great White,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1st August,2025.0,Unprovoked,Puerto Rico,Carolina,Carolina Beach,Wading,Eleonora Boi,F,39,...,Undetermined,Kevin McMurray Trackingsharks.com: NY Post,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7037,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7038,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7039,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7040,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7041,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [ ]:
shark_db = pd.read_excel(url)

shark_db.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,16th August 2025,2025.0,Provoked,USA,Florida,Cayo Costa Boca Grande,Fishing,Shawn Meuse,M,?,...,Lemon shark 1.8 m (6ft),Johannes Marchand: Kevin McMurray Trackingshar...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18th August,2025.0,Unprovoked,Australia,NSW,Cabarita Beach,Surfing,Brad Ross,M,?,...,5m (16.5ft) Great White,Bob Myatt GSAF The Guardian: 9 News: ABS News:...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17th August,2025.0,Unprovoked,Bahamas,Atlantic Ocean near Big Grand Cay,North of Grand Bahama near Freeport,Spearfishing,Not stated,M,63,...,Undetermined,Ralph Collier GSAF and Kevin MCMurray Tracking...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7th August,2025.0,Unprovoked,Australia,NSW,Tathra Beach,Surfing,Bowie Daley,M,9,...,Suspected Great White,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1st August,2025.0,Unprovoked,Puerto Rico,Carolina,Carolina Beach,Wading,Eleonora Boi,F,39,...,Undetermined,Kevin McMurray Trackingsharks.com: NY Post,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
shark_db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7042 entries, 0 to 7041
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7042 non-null   object
 1   Year            7040 non-null   float64
 2   Type            7024 non-null   object
 3   Country         6992 non-null   object
 4   State           6557 non-null   object
 5   Location        6475 non-null   object
 6   Activity        6457 non-null   object
 7   Name            6823 non-null   object
 8   Sex             6463 non-null   object
 9   Age             4048 non-null   object
 10  Injury          7007 non-null   object
 11  Fatal Y/N       6481 non-null   object
 12  Time            3516 non-null   object
 13  Species         3911 non-null   object
 14  Source          7022 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.2+ MB

Columns:

In [ ]:
shark_db.nunique()

Date              6086
Year               261
Type                13
Country            247
State              937
Location          4593
Activity          1606
Name              5767
Sex                 10
Age                250
Injury            4160
Fatal Y/N           12
Time               458
Species           1724
Source            5381
pdf               6789
href formula      6784
href              6776
Case Number       6777
Case Number.1     6775
original order    6797
Unnamed: 21          1
Unnamed: 22          2
dtype: int64

In [ ]:
shark_db.describe()

              Year  original order
count  7040.000000     6799.000000
mean   1935.621449     3401.152081
std     271.221061     1963.076319
min       0.000000        2.000000
25%    1948.000000     1701.500000
50%    1986.000000     3401.000000
75%    2010.000000     5100.500000
max    2026.000000     6802.000000

In [ ]:
shark_db.describe(include="all")

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
count,7042.0,7040.000000,7024,6992,6557,6475,6457,6823,6463,4048.0,...,3911,7022,6799,6794,6796,6798,6797,6799.000000,1,2
unique,6086.0,NaN,13,247,937,4593,1606,5767,10,250.0,...,1724,5381,6789,6784,6776,6777,6775,NaN,1,2
top,1957.0,NaN,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16.0,...,White shark,"K. McMurray, TrackingSharks.com",1916.12.08.a-b-German.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1920.00.00.b,2022.03.15,NaN,stopped here,Teramo
freq,9.0,NaN,5196,2570,1191,191,1138,679,5647,92.0,...,194,131,2,2,4,2,2,NaN,1,1
mean,NaN,1935.621449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3401.152081,NaN,NaN
std,NaN,271.221061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1963.076319,NaN,NaN
min,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN
25%,NaN,1948.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1701.500000,NaN,NaN
50%,NaN,1986.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3401.000000,NaN,NaN
75%,NaN,2010.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5100.500000,NaN,NaN
max,NaN,2026.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6802.000000,NaN,NaN

In [ ]:
shark_db.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,16th August 2025,2025.0,Provoked,USA,Florida,Cayo Costa Boca Grande,Fishing,Shawn Meuse,M,?,...,Lemon shark 1.8 m (6ft),Johannes Marchand: Kevin McMurray Trackingshar...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18th August,2025.0,Unprovoked,Australia,NSW,Cabarita Beach,Surfing,Brad Ross,M,?,...,5m (16.5ft) Great White,Bob Myatt GSAF The Guardian: 9 News: ABS News:...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17th August,2025.0,Unprovoked,Bahamas,Atlantic Ocean near Big Grand Cay,North of Grand Bahama near Freeport,Spearfishing,Not stated,M,63,...,Undetermined,Ralph Collier GSAF and Kevin MCMurray Tracking...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7th August,2025.0,Unprovoked,Australia,NSW,Tathra Beach,Surfing,Bowie Daley,M,9,...,Suspected Great White,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1st August,2025.0,Unprovoked,Puerto Rico,Carolina,Carolina Beach,Wading,Eleonora Boi,F,39,...,Undetermined,Kevin McMurray Trackingsharks.com: NY Post,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Plan of Action:

Date:
Choose from:
 - Drop the Date column completely
 - Leave the month as an indicator of how frequent attacks are
 - Separate the attack data by 21st and 20th century

Year:
 - Fill in the empty cells
 - Change from float to integer

Type:
 - Check for typing errors, duplicates, upper/lower case.

Country:
 - Check for typing errors, duplicates, upper/lower case.

State:
 - Decide the terminology of data.

Activity - No changes ?

Name:
 - Check for typing errors, duplicates, upper/lower case.

Sex:
 - Check for typing errors, duplicates, upper/lower case.

Age:
 - Check for typing errors, duplicates, upper/lower case.

Injury:

Fatal Y/N:
- Check if all cells are either Y or N.

Time:
- Standardize time format.
- Separate it by time of day (morning afternoon evening?)

Species:
- Check if there is a particular species of shark that is responsible for the most attacks.




Not in original spreadsheet when opened, dismiss?
Source
pdf
href formula
href
Case Number
Case Number.1
original order
Unnamed: 21
Unnamed: 22